A calculator program written in C
ALX-SE-Algorithmia/Demo-Project pull request #32
Opened 2023-07-12 11:01 UTC by Maryanemwende

2023-07-12 14:04 UTC, Certifieddonnie requested changes

2023-07-12 14:11 UTC, Certifieddonnie requested changes

2023-07-12 14:11 UTC, Certifieddonnie commented on maryanemwende/README.md
Let your Readme be well explained. I shouldn't ask you how to run it. Instead from your Readme, I should be able to know how to run the program on my end and see it works.

2023-07-12 16:06 UTC, Maryanemwende commented
Thank you for the review. I will make the necessary changes, it is still a
work in progress.

On Wed, 12 Jul 2023, 17:12 Amure McDonald, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On maryanemwende/README.md
> <https://github.com/ALX-SE-Algorithmia/Demo-Project/pull/32#discussion_r1261241059>
> :
>
> Let your Readme be well explained. I shouldn't ask you how to run it.
> Instead from your Readme, I should be able to know how to run the program
> on my end and see it works.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ALX-SE-Algorithmia/Demo-Project/pull/32#pullrequestreview-1526457866>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6AALMPAE67OVL6GG42WEWLXP2WDBANCNFSM6AAAAAA2HJ5XSQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-13 14:44 UTC, Maryanemwende commented
@Certifieddonnie I made the suggested changes and I am now ready for review. Thanks in advance.

2023-07-13 15:23 UTC, merged