bettcollins
ALX-SE-Algorithmia/Demo-Project pull request #37
Opened 2023-07-12 22:23 UTC by reecevinto

2023-07-13 05:45 UTC, Certifieddonnie requested changes

2023-07-13 05:45 UTC, Certifieddonnie commented on bettCollins/collins.md
Okay Nice README 💯 . You explained your code, which I understand. But I don't know how to run it. You might have to include the steps and guides on how a newbie can run the program without asking you.

2023-07-13 05:45 UTC, Certifieddonnie commented on bettCollins/bmicalc.c
Great Code, but no Betty docs styling and C99 styling isn't allowed with Betty.🤷

2023-07-13 18:31 UTC, MartyOfMCA commented
@reecevinto Also, I want you to know that your executable is still on this branch. Also, make the name of your directory name lowercase throughout

2023-07-16 16:35 UTC, reecevinto commented on bettCollins/collins.md
okay thank you for the review marty lemme change on that

2023-07-16 16:36 UTC, reecevinto commented on bettCollins/collins.md
donnie  i mean , thought it's marty

2023-07-17 12:06 UTC, closed without merging

2023-07-17 12:07 UTC, Certifieddonnie commented
I will close this, since you opened a new one👍